### PR TITLE
[CLOUD-2350] Container namespace switch

### PR DESCRIPTION
**Pull request by goldmann**
https://issues.jboss.org/browse/CLOUD-2350

### CODE REVIEW

**Review by spolti — COMMENTED** [review]
I'll leave it to @AntStephenson to approve. as he is dealing with osbs builds.

**Review by antncl — APPROVED** [review]

**Comment by antncl** [comment]
@goldmann I've approved these changes, please feel free to merge whenever appropriate. Can you confirm if we need to create extra git repos or did you already take care of that?

**Comment by goldmann** [comment]
@spolti No new repos required, existing repos will be migrated.

**Comment by spolti** [comment]
@AntStephenson

**Pull request merged**
